name: interpretable-ai
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - atomicwrites=1.3.0
  - attrs=19.3.0
  - backcall=0.1.0
  - backports=1.0
  - backports.os=0.1.1
  - backports.shutil_get_terminal_size=1.0.0
  - beautifulsoup4=4.8.1
  - bitarray=1.0.1
  - bkcharts=0.2
  - blas=1.0
  - bleach=3.1.0
  - blosc=1.16.3
  - bokeh=1.4.0
  - boto=2.49.0
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - cairo=1.16.0
  - certifi=2020.4.5.1
  - cffi=1.13.1
  - chardet=3.0.4
  - cloudpickle=1.2.2
  - clyent=1.2.2
  - colorama=0.4.1
  - cryptography=2.8
  - curl=7.65.3
  - cycler=0.10.0
  - cython=0.29.13
  - cytoolz=0.10.0
  - decorator=4.4.1
  - defusedxml=0.6.0
  - distributed=2.6.0
  - docutils=0.15.2
  - fontconfig=2.13.1
  - glib=2.63.1
  - glob2=0.7
  - gmp=6.1.2
  - gmpy2=2.0.8
  - graphviz=2.40.1
  - h5py=2.8.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - heapdict=1.0.1
  - html5lib=1.0.1
  - imageio=2.6.1
  - imagesize=1.1.0
  - importlib_metadata=0.23
  - intel-openmp=2019.4
  - ipykernel=5.1.3
  - ipython=7.9.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=4.3.21
  - itsdangerous=1.1.0
  - jasper=2.0.14
  - jbig=2.1
  - jdcal=1.4.1
  - jedi=0.15.1
  - jinja2=2.10.3
  - joblib=0.14.0
  - jpeg=9b
  - json5=0.8.5
  - jsonschema=3.1.1
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.0.0
  - jupyter_core=4.6.1
  - jupyterlab=1.1.4
  - jupyterlab_server=1.0.6
  - keyring=18.0.0
  - krb5=1.16.1
  - lazy-object-proxy=1.4.3
  - libarchive=3.3.3
  - libcurl=7.65.3
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libiconv=1.15
  - liblief=0.9.0
  - libopencv=3.4.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libsodium=1.0.16
  - libssh2=1.8.2
  - libtiff=4.1.0
  - libvpx=1.7.0
  - libxml2=2.9.9
  - libxslt=1.1.33
  - llvmlite=0.30.0
  - locket=0.2.0
  - lxml=4.4.1
  - lz4-c=1.8.1.2
  - lzo=2.10
  - matplotlib=3.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - mock=3.0.5
  - more-itertools=7.2.0
  - mpc=1.1.0
  - mpfr=4.0.1
  - mpmath=1.1.0
  - msgpack-python=0.6.1
  - multipledispatch=0.6.0
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - ncurses=6.1
  - networkx=2.4
  - nltk=3.4.5
  - nose=1.3.7
  - notebook=6.0.1
  - numba=0.46.0
  - numexpr=2.7.0
  - numpy=1.17.3
  - numpy-base=1.17.3
  - numpydoc=0.9.1
  - opencv=3.4.2
  - openpyxl=3.0.0
  - openssl=1.1.1g
  - packaging=19.2
  - pandas=0.25.2
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.5.1
  - partd=1.0.0
  - path.py=12.0.1
  - pathlib2=2.3.5
  - patsy=0.5.1
  - pcre=8.43
  - pep8=1.7.1
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.2.1
  - pip=19.3.1
  - pixman=0.38.0
  - pkginfo=1.5.0.1
  - psutil=5.6.3
  - ptyprocess=0.6.0
  - py=1.8.0
  - py-lief=0.9.0
  - py-opencv=3.4.2
  - pycodestyle=2.5.0
  - pycosat=0.6.3
  - pycparser=2.19
  - pycrypto=2.6.1
  - pycurl=7.43.0.3
  - pydotplus=2.0.2
  - pyflakes=2.1.1
  - pygments=2.4.2
  - pylint=2.4.3
  - pyodbc=4.0.27
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pyrsistent=0.15.4
  - pysocks=1.7.1
  - pytables=3.4.4
  - pytest=5.2.2
  - pytest-arraydiff=0.3
  - pytest-astropy=0.5.0
  - pytest-doctestplus=0.4.0
  - pytest-openfiles=0.4.0
  - pytest-remotedata=0.3.2
  - python=3.7.5
  - python-dateutil=2.8.1
  - python-libarchive-c=2.8
  - pytorch=1.4.0
  - pytz=2019.3
  - pywavelets=1.0.3
  - pyyaml=5.1.2
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtawesome=0.6.0
  - qtconsole=4.5.5
  - qtpy=1.9.0
  - readline=7.0
  - requests=2.22.0
  - rope=0.14.0
  - ruamel_yaml=0.15.46
  - scikit-image=0.15.0
  - scikit-learn=0.21.3
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=41.6.0
  - singledispatch=3.4.0.3
  - sip=4.19.8
  - six=1.12.0
  - snappy=1.1.7
  - snowballstemmer=2.0.0
  - sortedcollections=1.1.2
  - sortedcontainers=2.1.0
  - soupsieve=1.9.3
  - statsmodels=0.10.1
  - sympy=1.4
  - torchvision=0.5.0
  - urllib3=1.24.2
  - werkzeug=0.16.0
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - wurlitzer=1.0.3
  - xlrd=1.2.0
  - xlsxwriter=1.2.2
  - xlwt=1.3.0
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zict=1.0.0
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - anchor-exp==0.0.0.6
    - args==0.1.0
    - blis==0.4.1
    - catalogue==1.0.0
    - click==6.7
    - clint==0.5.1
    - cssselect2==0.3.0
    - cymem==2.0.3
    - future==0.18.2
    - ipdb==0.13.3
    - lime==0.1.1.37
    - pdpbox==0.2.0
    - prettytable==0.7.2
    - progressbar==2.5
    - progressbar2==3.47.0
    - pygam==0.8.0
    - python-utils==2.3.0
    - requests-toolbelt==0.9.1
    - scikit-plot==0.3.7
    - scipy==1.1.0
    - shap==0.35.0
    - srsly==1.0.2
    - svglib==1.0.0
    - tabulate==0.8.7
    - tqdm==4.43.0
    - llvm-openmp=4.0.1
    - libgfortran=3.0.1
    - libcxx=4.0.1
    - appnope=0.1.0
    - libcxxabi=4.0.1
    - python.app=2
    - xlwings=0.16.0
prefix: /Users/ajay/opt/anaconda3/envs/interpretable-ai
