name: interpretable-ai
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2019.03=py37_0
  - alabaster=0.7.12=py37_0
  - anaconda=custom=py37_1
  - anaconda-client=1.7.2=py37_0
  - anaconda-project=0.8.4=py_0
  - appnope=0.1.0=py37_0
  - appscript=1.1.0=py37h1de35cc_0
  - asn1crypto=1.2.0=py37_0
  - astroid=2.3.2=py37_0
  - astropy=3.2.3=py37h1de35cc_0
  - atomicwrites=1.3.0=py37_1
  - attrs=19.3.0=py_0
  - babel=2.7.0=py_0
  - backcall=0.1.0=py37_0
  - backports=1.0=py_2
  - backports.os=0.1.1=py37_0
  - backports.shutil_get_terminal_size=1.0.0=py37_2
  - beautifulsoup4=4.8.1=py37_0
  - bitarray=1.0.1=py37h1de35cc_0
  - bkcharts=0.2=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - blosc=1.16.3=hd9629dc_0
  - bokeh=1.4.0=py37_0
  - boto=2.49.0=py37_0
  - bottleneck=1.2.1=py37h1d22016_1
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2021.4.13=hecd8cb5_1
  - cairo=1.16.0=h0ab9d94_1001
  - certifi=2020.12.5=py37hecd8cb5_0
  - cffi=1.13.1=py37hb5b8e2f_0
  - chardet=3.0.4=py37_1003
  - cloudpickle=1.2.2=py_0
  - clyent=1.2.2=py37_1
  - colorama=0.4.1=py37_0
  - contextlib2=0.6.0=py_0
  - cryptography=2.8=py37ha12b0ac_0
  - curl=7.65.3=ha441bb4_0
  - cycler=0.10.0=py37_0
  - cython=0.29.13=py37h0a44026_0
  - cytoolz=0.10.0=py37h1de35cc_0
  - dask=2.6.0=py_0
  - dask-core=2.6.0=py_0
  - dbus=1.13.12=h90a0687_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - distributed=2.6.0=py_0
  - docutils=0.15.2=py37_0
  - entrypoints=0.3=py37_0
  - et_xmlfile=1.0.1=py37_0
  - expat=2.2.6=h0a44026_0
  - fastcache=1.1.0=py37h1de35cc_0
  - ffmpeg=4.0=h01ea3c9_0
  - filelock=3.0.12=py_0
  - flask=1.1.1=py_0
  - fontconfig=2.13.1=h1027ab8_1000
  - freetype=2.9.1=hb4e5f40_0
  - fribidi=1.0.5=h01d97ff_1002
  - fsspec=0.5.2=py_0
  - get_terminal_size=1.0.0=h7520d66_0
  - gettext=0.19.8.1=h15daf44_3
  - gevent=1.4.0=py37h1de35cc_0
  - glib=2.63.1=hd977a24_0
  - glob2=0.7=py_0
  - gmp=6.1.2=hb37e062_1
  - gmpy2=2.0.8=py37h6ef4df4_2
  - graphite2=1.3.13=h2098e52_1000
  - graphviz=2.40.1=hefbbd9a_2
  - greenlet=0.4.15=py37h1de35cc_0
  - harfbuzz=1.8.8=hb8d4a28_0
  - hdf5=1.10.2=hfa1e0ec_1
  - heapdict=1.0.1=py_0
  - html5lib=1.0.1=py37_0
  - icu=58.2=h4b95b61_1
  - idna=2.8=py37_0
  - imageio=2.6.1=py37_0
  - imagesize=1.1.0=py37_0
  - importlib_metadata=0.23=py37_0
  - intel-openmp=2019.4=233
  - ipykernel=5.1.3=py37h39e3cac_0
  - ipython=7.9.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py37_0
  - itsdangerous=1.1.0=py37_0
  - jasper=2.0.14=h636a363_1
  - jbig=2.1=h4d881f8_0
  - jdcal=1.4.1=py_0
  - jedi=0.15.1=py37_0
  - jinja2=2.10.3=py_0
  - joblib=0.14.0=py_0
  - jpeg=9b=he5867d9_2
  - json5=0.8.5=py_0
  - jsonschema=3.1.1=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.3.4=py37_0
  - jupyter_console=6.0.0=py37_0
  - jupyter_core=4.6.1=py37_0
  - jupyterlab=1.1.4=pyhf63ae98_0
  - jupyterlab_server=1.0.6=py_0
  - keyring=18.0.0=py37_0
  - kiwisolver=1.1.0=py37h0a44026_0
  - krb5=1.16.1=hddcf347_7
  - lazy-object-proxy=1.4.3=py37h1de35cc_0
  - libarchive=3.3.3=h786848e_5
  - libcurl=7.65.3=h051b688_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - liblief=0.9.0=h2a1bed3_2
  - libopencv=3.4.2=h7c891bd_1
  - libopus=1.3.1=h1de35cc_0
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.16=h3efe00b_0
  - libssh2=1.8.2=ha12b0ac_0
  - libtiff=4.1.0=hcb84e12_0
  - libvpx=1.7.0=h378b8a2_0
  - libxml2=2.9.9=hf6e021a_1
  - libxslt=1.1.33=h33a18ac_0
  - llvm-openmp=4.0.1=hcfea43d_1
  - llvmlite=0.30.0=py37h98b8051_0
  - locket=0.2.0=py37_1
  - lxml=4.4.1=py37hef8c89e_0
  - lz4-c=1.8.1.2=h1de35cc_0
  - lzo=2.10=h362108e_2
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib=3.1.1=py37h54f8f79_0
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.15=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - mock=3.0.5=py37_0
  - more-itertools=7.2.0=py37_0
  - mpc=1.1.0=h6ef4df4_1
  - mpfr=4.0.1=h3018a27_3
  - mpmath=1.1.0=py37_0
  - msgpack-python=0.6.1=py37h04f5b5a_1
  - multipledispatch=0.6.0=py37_0
  - nbconvert=5.6.1=py37_0
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=h0a44026_1
  - networkx=2.4=py_0
  - ninja=1.9.0=py37h04f5b5a_0
  - nltk=3.4.5=py37_0
  - nose=1.3.7=py37_2
  - notebook=6.0.1=py37_0
  - numba=0.46.0=py37h6440ff4_0
  - numexpr=2.7.0=py37h7413580_0
  - numpy=1.17.3=py37h4174a10_0
  - numpy-base=1.17.3=py37h6575580_0
  - numpydoc=0.9.1=py_0
  - olefile=0.46=py37_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openpyxl=3.0.0=py_0
  - openssl=1.1.1k=h9ed2024_0
  - packaging=19.2=py_0
  - pandas=0.25.2=py37h0a44026_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - pango=1.42.4=h060686c_0
  - parso=0.5.1=py_0
  - partd=1.0.0=py_0
  - path.py=12.0.1=py_0
  - pathlib2=2.3.5=py37_0
  - patsy=0.5.1=py37_0
  - pcre=8.43=h0a44026_0
  - pep8=1.7.1=py37_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=6.2.1=py37hb68e598_0
  - pip=19.3.1=py37_0
  - pixman=0.38.0=h01d97ff_1003
  - pkginfo=1.5.0.1=py37_0
  - pluggy=0.13.0=py37_0
  - ply=3.11=py37_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.10=py_0
  - psutil=5.6.3=py37h1de35cc_0
  - ptyprocess=0.6.0=py37_0
  - py=1.8.0=py37_0
  - py-lief=0.9.0=py37h1413db1_2
  - py-opencv=3.4.2=py37h7c891bd_1
  - pycodestyle=2.5.0=py37_0
  - pycosat=0.6.3=py37h1de35cc_0
  - pycparser=2.19=py37_0
  - pycrypto=2.6.1=py37h1de35cc_9
  - pycurl=7.43.0.3=py37ha12b0ac_0
  - pydotplus=2.0.2=pyhd1c1de3_3
  - pyflakes=2.1.1=py37_0
  - pygments=2.4.2=py_0
  - pylint=2.4.3=py37_0
  - pyodbc=4.0.27=py37h0a44026_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py37h655552a_2
  - pyrsistent=0.15.4=py37h1de35cc_0
  - pysocks=1.7.1=py37_0
  - pytables=3.4.4=py37h13cba08_0
  - pytest=5.2.2=py37_0
  - pytest-arraydiff=0.3=py37h39e3cac_0
  - pytest-astropy=0.5.0=py37_0
  - pytest-doctestplus=0.4.0=py_0
  - pytest-openfiles=0.4.0=py_0
  - pytest-remotedata=0.3.2=py37_0
  - python=3.7.5=h359304d_0
  - python-dateutil=2.8.1=py_0
  - python-libarchive-c=2.8=py37_13
  - python.app=2=py37_9
  - pytz=2019.3=py_0
  - pywavelets=1.0.3=py37h1d22016_1
  - pyyaml=5.1.2=py37h1de35cc_0
  - pyzmq=18.1.0=py37h0a44026_0
  - qt=5.9.7=h468cd18_1
  - qtawesome=0.6.0=py_0
  - qtconsole=4.5.5=py_0
  - qtpy=1.9.0=py_0
  - readline=7.0=h1de35cc_5
  - requests=2.22.0=py37_0
  - rope=0.14.0=py_0
  - ruamel_yaml=0.15.46=py37h1de35cc_0
  - scikit-image=0.15.0=py37h0a44026_0
  - seaborn=0.9.0=py37_0
  - send2trash=1.5.0=py37_0
  - setuptools=41.6.0=py37_0
  - simplegeneric=0.8.1=py37_2
  - singledispatch=3.4.0.3=py37_0
  - sip=4.19.8=py37h0a44026_0
  - snappy=1.1.7=he62c110_3
  - snowballstemmer=2.0.0=py_0
  - sortedcollections=1.1.2=py37_0
  - sortedcontainers=2.1.0=py37_0
  - soupsieve=1.9.3=py37_0
  - sphinx=2.2.1=py_0
  - sphinxcontrib=1.0=py37_1
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.3=py_0
  - sphinxcontrib-websupport=1.1.2=py_0
  - spyder=3.3.6=py37_0
  - spyder-kernels=0.5.2=py37_0
  - sqlalchemy=1.3.10=py37h1de35cc_0
  - sqlite=3.30.1=ha441bb4_0
  - statsmodels=0.10.1=py37h1d22016_0
  - sympy=1.4=py37_0
  - tbb=2019.8=h04f5b5a_0
  - tblib=1.5.0=py_0
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py37_0
  - tk=8.6.8=ha441bb4_0
  - toolz=0.10.0=py_0
  - torchvision=0.5.0=py37_cpu
  - tornado=6.0.3=py37h1de35cc_0
  - traitlets=4.3.3=py37_0
  - unicodecsv=0.14.1=py37_0
  - unixodbc=2.3.7=h1de35cc_0
  - urllib3=1.24.2=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - werkzeug=0.16.0=py_0
  - widgetsnbextension=3.5.1=py37_0
  - wurlitzer=1.0.3=py37_0
  - xlrd=1.2.0=py37_0
  - xlsxwriter=1.2.2=py_0
  - xlwings=0.16.0=py37_0
  - xlwt=1.3.0=py37_0
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zeromq=4.3.1=h0a44026_3
  - zict=1.0.0=py_0
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
  - pip:
    - absl-py==0.13.0
    - alibi==0.6.0
    - anchor-exp==0.0.0.6
    - args==0.1.0
    - astunparse==1.6.3
    - blis==0.4.1
    - cached-property==1.5.2
    - cachetools==4.2.2
    - catalogue==1.0.0
    - click==6.7
    - clint==0.5.1
    - cssselect2==0.3.0
    - cymem==2.0.3
    - dice-ml==0.6.1
    - dill==0.3.4
    - en-core-web-sm==2.2.5
    - fairlearn==0.6.2
    - flatbuffers==1.12
    - floyd-cli==0.11.17
    - future==0.18.2
    - gast==0.4.0
    - gensim==4.0.1
    - google-auth==1.34.0
    - google-auth-oauthlib==0.4.5
    - google-pasta==0.2.0
    - grpcio==1.34.1
    - h5py==3.1.0
    - huggingface-hub==0.0.12
    - ipdb==0.13.3
    - keras-nightly==2.5.0.dev2021032900
    - keras-preprocessing==1.1.2
    - lime==0.1.1.37
    - markdown==3.3.4
    - marshmallow==2.21.0
    - mmh3==3.0.0
    - murmurhash==1.0.2
    - murmurhash2==0.2.9
    - oauthlib==3.1.1
    - opt-einsum==3.3.0
    - pdfkit==0.6.1
    - pdpbox==0.2.0
    - plac==1.1.3
    - preshed==3.0.2
    - prettytable==0.7.2
    - progressbar==2.5
    - progressbar2==3.47.0
    - protobuf==3.17.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygam==0.8.0
    - python-utils==2.3.0
    - raven==6.10.0
    - regex==2021.7.6
    - reportlab==3.5.42
    - requests-oauthlib==1.3.0
    - requests-toolbelt==0.9.1
    - rsa==4.7.2
    - sacremoses==0.0.45
    - scikit-learn==0.24.2
    - scikit-plot==0.3.7
    - scipy==1.6.3
    - sentencepiece==0.1.95
    - shap==0.39.0
    - six==1.15.0
    - slicer==0.0.7
    - smart-open==5.0.0
    - spacy==2.2.4
    - spacy-lookups-data==0.1.0
    - srsly==1.0.2
    - svglib==1.0.0
    - tabulate==0.8.7
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.5.0
    - tensorflow-estimator==2.5.0
    - termcolor==1.1.0
    - thinc==7.4.0
    - threadpoolctl==2.1.0
    - tinycss2==1.0.2
    - tokenizers==0.10.3
    - torch==1.8.1
    - torchtext==0.9.1
    - tqdm==4.43.0
    - transformers==4.9.1
    - typed-ast==1.4.1
    - typing-extensions==3.10.0.0
    - wasabi==0.6.0
    - wheel==0.36.2
    - wordcloud==1.8.1
    - wrapt==1.12.1
prefix: /Users/ajay/opt/anaconda3/envs/interpretable-ai

